name: LW-MoneySystem
main: net.lvckyworld.moneysystem.LWMoneySystem
version: 1.2
author: Iven S. Lukas Oe.
commands:
  pay:
    description: Pay People for BlowJobs
  balance:
    description: Shows your Balance
    aliases: b
  setmoney:
    description: Set Players money
    aliases: sm
  addmoney:
    description: Add Money to a Player
    aliases: am
  moneysystem:
    description: Shows Help-Page
    aliases: ms